eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
security:
  user:
    password: password
---
spring:
  profiles: heroku
#eureka:
#  instance:
#    hostname: localhost:5000
#    nonSecurePort: 80
#  password: password